### ISSUE TITLE
是否支持 THUDM/chatglm2-6b-32k的加速

### ISSUE THREAD

**Issue by wangschang** [ztxz16/fastllm#225]
修改model后一直不返回信息

**Comment by wangschang** [comment]
> 

那应该是支持对吧 
我这里返回model有问题 6b和6b-32k都返回一样的问题  AttributeError: 'model' object has no attribute 'config'`
谢谢
代码如下：
`ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/miniconda3/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/miniconda3/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/miniconda3/lib/python3.8/site-packages/fastapi/applications.py", line 289, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/miniconda3/lib/python3.8/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/miniconda3/lib/python3.8/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/miniconda3/lib/python3.8/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/miniconda3/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/miniconda3/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/miniconda3/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/usr/local/miniconda3/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/miniconda3/lib/python3.8/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/miniconda3/lib/python3.8/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/miniconda3/lib/python3.8/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/usr/local/miniconda3/lib/python3.8/site-packages/fastapi/routing.py", line 273, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/miniconda3/lib/python3.8/site-packages/fastapi/routing.py", line 190, in run_endpoint_function
    return await dependant.call(**values)
  File "api_new.py", line 45, in create_item
    model = llm.from_hf(model, tokenizer, dtype = "float16")#加速 float16 int8 int4
  File "/usr/local/miniconda3/lib/python3.8/site-packages/fastllm_pytools-0.0.1-py3.8.egg/fastllm_pytools/llm.py", line 91, in from_hf
    return hf_model.create(model, tokenizer, dtype = dtype);
  File "/usr/local/miniconda3/lib/python3.8/site-packages/fastllm_pytools-0.0.1-py3.8.egg/fastllm_pytools/hf_model.py", line 29, in create
    modelInfo = model.config.__dict__
AttributeError: 'model' object has no attribute 'config'`

**Comment by allendred** [comment]
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:15<00:00,  2.17s/it]
convert ( 200 / 200 )
Warmup...
status = 1
1 16 128
Error: cublas error.
Aborted (core dumped)

**Comment by wangschang** [comment]
> 

请问是如何解决的 需要修改什么吗

**Comment by allendred** [comment]
用容器部署的,我重启容器就好了,但是长文本效果不行

**Comment by wangschang** [comment]
已解决是因为位置放的有问题 
放在初始化后每次调用就可以了
