### ISSUE TITLE
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

### ISSUE THREAD

**Issue by ArtificialZeng** [ztxz16/fastllm#231]
Traceback (most recent call last):
  File "/home/zengzijian/ai_code/fastllm/build/tools/baichuan2flm.py", line 18, in <module>
    torch2flm.tofile(exportPath, model, tokenizer, dtype = dtype)
  File "/home/zengzijian/ai_code/fastllm/build/tools/fastllm_pytools/torch2flm.py", line 156, in tofile
    cur = dict[key].numpy().astype(ori_np_data_type)
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

**Comment by ztxz16** [comment]
这个有点奇怪，有改过脚本吗？baichuan的脚本里11行已经model.to("cpu")，为什么这里还是在cuda:0上

**Comment by TylunasLi** [comment]
正常的baichuan转换如楼上所说是做过model.to("cpu")的，其他模型，如果model.to("cpu")不成功，可以在这里加一下，改为：
```python
dict[key].cpu().numpy().astype(ori_np_data_type)
```
