### ISSUE TITLE
支持chatglm2-6b-32k吗

### ISSUE THREAD

**Issue by ZTurboX** [ztxz16/fastllm#283]
支持chatglm2-6b-32k吗

**Comment by renllll** [comment]
请问你成功了吗，我运行的时候报以下错误
You shouldn't move a model when it is dispatched on multiple devices.
Traceback (most recent call last):
  File "web_demo3.py", line 8, in &lt;module&gt;
    model = llm.from_hf(model, tokenizer, dtype = "float16")# dtype支持 "float16", "int8", "int4"
  File "/home/remotesense/anaconda3/envs/glm/lib/python3.8/site-packages/fastllm_pytools-0.0.1-py3.8.egg/fastllm_pytools/llm.py", line 94, in from_hf
    return hf_model.create(model, tokenizer, dtype = dtype);
  File "/home/remotesense/anaconda3/envs/glm/lib/python3.8/site-packages/fastllm_pytools-0.0.1-py3.8.egg/fastllm_pytools/hf_model.py", line 84, in create
    if len(active_adapter) != 0:
TypeError: object of type 'method' has no len()
