### ISSUE TITLE
/home/jwkj/miniconda3/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.30' not found 

### ISSUE THREAD

**Issue by zxzxde** [ztxz16/fastllm#339]
Traceback (most recent call last):
  File "/home/GC/Gits/Baichuan2/test_fastllm.py", line 5, in <module>
    from fastllm_pytools import llm
  File "/home/GC/Gits/Baichuan2/venv/lib/python3.11/site-packages/fastllm_pytools-0.0.1-py3.11.egg/fastllm_pytools/llm.py", line 11, in <module>
    fastllm_lib = ctypes.cdll.LoadLibrary(os.path.join(os.path.split(os.path.realpath(__file__))[0], "libfastllm_tools.so"))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jwkj/miniconda3/lib/python3.11/ctypes/__init__.py", line 454, in LoadLibrary
    return self._dlltype(name)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/jwkj/miniconda3/lib/python3.11/ctypes/__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: /home/jwkj/miniconda3/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /home/GC/Gits/Baichuan2/venv/lib/python3.11/site-packages/fastllm_pytools-0.0.1-py3.11.egg/fastllm_pytools/libfastllm_tools.so)

奇怪，系统安装了miniconda3, 但是环境使用的还是venv,为什么到miniconda上去了。
/lib/x86_64-linux-gnu目录下没有libstdc++.so.6

**Comment by exceedzhang** [comment]
遇到类似问题，有谁知道如何解决吗？

**Comment by Whylickspittle** [comment]
更新 GCC：
sudo apt update
sudo apt install build-essential
sudo apt install gcc

再软链接新版本的 libstdc++：
sudo ln -sf /usr/lib/x86_64-linux-gnu/libstdc++.so.6 /opt/conda/lib/libstdc++.so.6
