### ISSUE TITLE
hf 模型转 llm模型时报错

### ISSUE THREAD

**Issue by ray-008** [ztxz16/fastllm#54]
使用如下命令安装fastllm_pytools包
```
cd fastllm
mkdir build
cd build
cmake .. -DUSE_CUDA=ON
make -j
cd tools && python setup.py install

from transformers import AutoTokenizer, AutoModel
tokenizer = AutoTokenizer.from_pretrained("THUDM/chatglm2-6b", trust_remote_code = True)
model = AutoModel.from_pretrained("THUDM/chatglm2-6b", trust_remote_code = True)
from fastllm_pytools import llm
model = llm.from_hf(model, tokenizer, dtype = "float16") 

```

```
root@7c296f76e678:/home/user/code/build/tools# python3
Python 3.10.6 (main, May 16 2023, 09:56:28) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from transformers import AutoTokenizer, AutoModel
>>> model='/home/user/code/chatglm2-6b'
>>> tokenizer = AutoTokenizer.from_pretrained(model, trust_remote_code = True)
>>> model = AutoModel.from_pretrained(model, trust_remote_code = True)
Loading checkpoint shards:  71%|████████████████████████████████████████               | 4/7 [00:07<00:05,  1.77s/it 
Loading checkpoint shards:  86%|████████████████████████████████████████                                                                                     
Loading checkpoint shards: 100%|████████████████████████████████████████                                                                                     
Loading checkpoint shards: 100%|████████████████████████████████████████              | 7/7 [00:11<00:00,  1.68s/it]
>>> from fastllm_pytools import llm
>>> model = llm.from_hf(model, tokenizer, dtype = "float16")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/code/build/tools/fastllm_pytools/llm.py", line 35, in from_hf
    return hf_model.create(model, tokenizer, dtype = dtype);
  File "/home/user/code/build/tools/fastllm_pytools/hf_model.py", line 49, in create
    model_type = model.config.__dict__["model_type"];
KeyError: 'model_type'
```

使用的 ChatGLM2 模型，`model = llm.from_hf(model, tokenizer, dtype = "float16")` 这一步报错了

**Comment by ztxz16** [comment]
这个模型是原生模型吗，你看一下hf文件夹里的config.json里有model_type吗

**Comment by ray-008** [comment]
找到原因了，是我下的模型比较早，chatglm2后面又更新了一些文件。 我重新下载了模型就好了。 
非常感谢🙏🏻，刚刚测试了，推理速度提高了好多。
